---

- hosts: all
  
  vars:
    - name: ssh_repo
    - name: dest

  tasks: 
    - name: copy key
      copy:     
        src: files/git_id_rsa.key
        dest: /tmp/git_id_rsa.key
        mode: 0600
        
    - name: install the latest version of git
      package:
        name:  git
        state: latest
    
    - name: Git pull
      git:
        repo: "{{ ssh_repo }}"
        dest: "{{ dest }}"
        version: "master"
        accept_hostkey: yes
        remote: origin
        force: yes
        key_file: /tmp/git_id_rsa.key
        
